/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ertSol from "./ERT.sol";
export type { ertSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DeusBridge } from "./DeusBridge";
